---

# box: ubuntu/focal64
# hostname: ubuntu-20.04

# vmname: 'demo6'
# memory: '512'
# cpus: '1'
# ip: '192.168.0.50'

script_path: 'scripts'

machines:
  -  ['s1.formation.lan', '192.168.0.11', '512', '1', 'ubuntu/focal64'] #ubuntu/focal64
  # -  ['s2.formation.lan', '192.168.0.12', '512', '1', 'ubuntu/focal64'] #centos8
  # -  ['s3.formation.lan', '192.168.0.13', '512', '1', 'ubuntu/focal64'] #ubuntu/focal64